import Head from "next/head";
import * as React from "react";
import Cards from "../components/cards/Cards";
import SearchBar from "../components/searchBar/SearchBar";
import { Data } from "../constant/Data";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [searchterm, setSearchterm] = React.useState("");
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headerImg}>
        <img src="/images/super-rob.png" alt="header-img" />
      </div>
      <SearchBar
        onChange={(event) => {
          setSearchterm(event.target.value);
        }}
      />

      <div className={styles.flexCards}>
        {Data.filter((val) => {
          if (searchterm === "") {
            return val;
          } else if (
            val.name.toLowerCase().includes(searchterm.toLowerCase())
          ) {
            return val;
          }
        }).map((val) => {
          return (
            <>
              <Cards
                key={val.id}
                image={val.image}
                name={val.name}
                place={val.place}
              />
            </>
          );
        })}
      </div>
    </div>
  );
}
